# https://github.com/TaouMou/starship-presets/blob/main/starship_text.toml

format = """\
[╭╴](fg:arrow)\
$username\
$hostname\
(\
    $directory\
)\
$git_branch\
$git_status\
$fill\
$cmd_duration\
(\
    $nodejs\
    $python\
    $golang\
    $docker_context
)
[╰─](fg:arrow)$character\
"""
# Add the modules you need

# Disable the blank line at the start of the prompt
add_newline = true

command_timeout = 2000

palette = "normal"


[palettes.normal]
arrow = "#EDF2F4"
os = "#16f4d0"
os_admin = "#e4ff1a"
directory = "#9ffff5"
time = "#bdfffd"
node = "#a5e6ba"
git = "#f17f29"
git_status = "#DFEBED"
python = "#edf67d"
golang = "#79d4fe"
clang = "#caf0f8"
duration = "#ce4257"
text_color = "#EDF2F4"
text_light = "#26272A"


[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '\[[$user](fg:$style)'
disabled = false
show_always = true

[hostname]
format = '@[$hostname]($style)\]'
style = 'bold os_admin'
ssh_only = false


[character]
success_symbol = "[󰍟](fg:arrow)"
error_symbol = "[󰍟](fg:red)"

[package]
disabled=true

[fill]
symbol = " "


# [directory]
# format = "[$path](bold $style)[$read_only]($read_only_style) "
# truncation_length = 0
# style = "fg:directory"
# read_only_style = "fg:directory"
# before_repo_root_style = "fg:directory"
# truncate_to_repo = false
# read_only ="  "

[directory]
truncation_length = 5
truncate_to_repo = false
fish_style_pwd_dir_length = 0
use_logical_path = false
format = '[$path]($style) [$read_only]($read_only_style)'
style = 'fg:85 bold'
disabled = false
read_only = ''
read_only_style = 'red'
truncation_symbol = '.../'
home_symbol = '~'

[time]
disabled = true
format = "at [󱑈 $time]($style)"
time_format = "%H:%M"
style = "bold fg:time"

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'

# [cmd_duration]
# format = "took [ $duration]($style) "
# style = "bold fg:duration"
# min_time = 10_10        # Show command duration over 10,00 milliseconds (=1 sec)


# ~/.config/starship.toml

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

# https://gist.github.com/akshay-na/2c37a8d21d8abd249543851178f37c0d
[git_status]
ahead = "↑${count} "
behind = "↓${count} "
diverged = "↕${ahead_count} ${behind_count}"
untracked = "?${count} "
modified = "!${count} "
conflicted = "≠ ${count} "
staged = "✓${count} "
stashed = "*${count} "
style = "bright-white"
format = """\
[$ahead_behind](bold green)\
[$stashed](bold green)\
[$behind_behind](bold red)\
[$diverged](bold yellow)\
[$conflicted](bold red)\
[$modified](bold blue)\
[$untracked](bold cyan)\
[$staged](bold green)\
"""


[nodejs]
format = "[ $symbol$version ]($style)"
style = "bg:node fg:text_light"
symbol = " "
version_format = "${raw}"
disabled=false
detect_extensions = ['js', 'mjs', 'cjs', 'ts']
detect_files = ['package.json', '.node-version', '.nvmrc']
detect_folders = ['node_modules']

[python]
format = '[ ${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
style = "bg:python fg:text_light"
symbol = " "
version_format = "${raw}"
disabled=false

[golang]
format = '[ $symbol($version )($mod_version )]($style)'
style = "bg:golang fg:text_light"
symbol = " "

[docker_context]
format = '[ $symbol$context](blue bold)'
# [aws]
# format = '[($profile)(\($region\))(\[$duration\])]($style)'
