"$schema" = 'https://starship.rs/config-schema.json'

# https://github.com/TaouMou/starship-presets/blob/main/starship_text.toml

# Disable the blank line at the start of the prompt
add_newline = true

format = """\
[╭╴](fg:arrow)\
$os\
$username\
$hostname\
(\
    $directory\
)\
$cmd_duration\
${custom.giturl}\
$git_branch\
$git_status\
(\
    $package\
    $nodejs\
    $deno\
    $bun\
    $conda\
    $python\
    $golang\
    $perl\
    $php\
    $dart\
    $lua\
    $rust\
    $c\
    $cmake\
    $dotnet\
    $java\
    $julia\
    $kotlin\
    $swift\
    $pulumi\
    $terraform\
    $docker_context\
    $kubernetes\
    $aws\
    $gcloud\
)
[╰─](fg:arrow)$character\
"""

command_timeout = 5000

right_format = """$all"""

palette = "normal"

[palettes.normal]
arrow = "#EDF2F4"
os = "#5ccfe6"
os_admin = "#6679a4"
directory = "#bae67e"
time = "#bdfffd"
node = "#68a063"
git = "#f17f29"
git_status = "#DFEBED"
python = "ffde57"
golang = "#00add8"
clang = "#0280cd"
swift = "#f15138"
lua = "#5959a5"
duration = "#ce4257"
text_color = "#EDF2F4"
text_light = "#26272A"
purple = "#c3a6ff"

[os]
disabled = false
format = ' [$symbol]($style)'

[os.symbols]
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Linux = " "
Macos = " "
openSUSE = " "
Redhat = " "
RedHatEnterprise = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[username]
format = '\[[$user@]($style)'
show_always = true
style_user = 'bold os'
style_root = 'bold os_admin'

[hostname]
ssh_symbol = "󰣀 "
ssh_only = false
format = '[$ssh_symbol$hostname]($style)\]'
style = 'os'

[character]
success_symbol = "[󰍟](fg:arrow)"
error_symbol = "[󰍟](fg:red)"

[package]
disabled = true

[directory]
read_only = " 󰌾"
truncation_length = 100
truncate_to_repo = false
style = " fg:directory"
format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[time]
disabled = true
format = "at [󱑈 $time]($style)"
time_format = "%H:%M"
style = "bold fg:time"

[cmd_duration]
min_time = 1000
format = 'took [$duration](bold yellow)'

[git_branch]
symbol = " "
format = ' [$symbol$branch]($style) '

# https://gist.github.com/akshay-na/2c37a8d21d8abd249543851178f37c0d
[git_status]
ahead = "↑${count} "
behind = "↓${count} "
diverged = "↕${ahead_count} ${behind_count}"
untracked = "?${count} "
modified = "!${count} "
conflicted = "≠ ${count} "
staged = "✓${count} "
stashed = "*${count} "
style = "bright-white"
format = """\
[$ahead_behind](bold green)\
[$stashed](bold green)\
[$behind_behind](bold red)\
[$diverged](bold yellow)\
[$conflicted](bold red)\
[$modified](bold blue)\
[$untracked](bold cyan)\
[$staged](bold green)\
"""

[nodejs]
symbol = " "
format = ' [$symbol($version)]($style)'
style = "bold fg:node"

[bun]
format = '[$symbol($version)]($style)'


[deno]
format = '\[[$symbol($version)]($style)\]'

[lua]
symbol = " "
format = ' [$symbol($version)]($style)'
style = "fg:lua"

[conda]
symbol = " "
format = ' [$symbol$environment]($style)'

[python]
symbol = " "
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[golang]
symbol = " "
format = ' [$symbol($version)]($style)'

[rust]
disabled = true
symbol = " "
format = ' [$symbol($version)]($style)'

[c]
symbol = " "
format = ' [$symbol($version(-$name))]($style)'
style = "fg:clang"

[cmake]
format = '[$symbol($version)]($style)'

[swift]
format = '[ $symbol($version)]($style)'
style = "fg:swift"

[dotnet]
format = ' [$symbol($version)($tfm)]($style)'

[perl]
format = '[$symbol($version)]($style)'

[php]
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[java]
symbol = " "
format = ' [$symbol($version)]($style)'
style = "fg:red"

[julia]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[pulumi]
format = ' [$symbol$stack]($style)'

[terraform]
format = ' [$symbol$workspace]($style)'

# [docker_context]
# symbol = " "
# format = ' [$symbol$context]($style) '

[docker_context]
disabled = false
symbol = ' '
style = 'fg:#06969A'
format = ' [$symbol$context]($style) '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
only_with_files = true
detect_extensions = ['Dockerfile']

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[aws]
disabled = true
symbol = " "
format = ' [$symbol($profile)(\($region\))(\[$duration\])]($style) '
style = "fg:aws"

[gcloud]
symbol = " "
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
disabled = true
